Add ANSI / Unicode side by side build support, integrate `CheckLimitlessCluster` (#52)
* Call CheckLimitlessCluster after a successful connection

* Add ansi unicode side by side build support for Windows

* Add ansi unicode side by side build support for macOS and Linux

* Update aws-rds-odbc submodule commit

* Dockerized test updates
- Put aws-rds-odbc in LD_LIBRARY_PATH
- Run ldd on driver to ensure it will load during test
- Upgrade Ubuntu to latest LTS version

diff --git a/linux/buildall b/linux/buildall
--- a/linux/buildall
+++ b/linux/buildall
@@ -48,21 +48,41 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-# Prep the aws-rds-odbc build
-echo "Prepping the aws-rds-odbc build"
-cmake -S . -B build > ./cmake.log 2>&1
+# Prep the aws-rds-odbc builds
+echo "Prepping the ansi aws-rds-odbc build"
+cmake -S . -B build_ansi > ./cmake.log 2>&1
 if [ $? -ne 0 ]; then
-  echo "aws-rds-odbc build prep failed"
+  echo "ansi aws-rds-odbc build prep failed"
+  echo "cmake.log:"
+  cat ./cmake.log
+  exit 1
+fi
+
+echo "Prepping the unicode aws-rds-odbc build"
+cmake -S . -B build_unicode -DUNICODE_BUILD=ON > ./cmake.log 2>&1
+if [ $? -ne 0 ]; then
+  echo "unicode aws-rds-odbc build prep failed"
   echo "cmake.log:"
   cat ./cmake.log
   exit 1
 fi
 
 # Build aws-rds-odbc
-echo "Building aws-rds-odbc"
-cmake --build build --config ${CONFIGURATION}
+echo "Building ansi version of aws-rds-odbc"
+cmake --build build_ansi --config ${CONFIGURATION} > ./cmake.log 2>&1
 if [ $? -ne 0 ]; then
-  echo "aws-rds-odbc build failed"
+  echo "ansi aws-rds-odbc build failed"
+  echo "cmake.log:"
+  cat ./cmake.log
+  exit 1
+fi
+
+echo "Building unicode version of aws-rds-odbc"
+cmake --build build_unicode --config ${CONFIGURATION} > ./cmake.log 2>&1
+if [ $? -ne 0 ]; then
+  echo "unicode aws-rds-odbc build failed"
+  echo "cmake.log:"
+  cat ./cmake.log
   exit 1
 fi
 
